# Generated by Django 4.2.2 on 2023-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Completed', models.BooleanField(default=False)),
                ('Startdate', models.DateTimeField()),
                ('Enddate', models.DateTimeField()),
                ('taskcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
