# Generated by Django 4.2.2 on 2023-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='Startdate',
            field=models.DateField(),
        ),
    ]
