# Generated by Django 4.2.2 on 2023-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_enddate_alter_task_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Startdate',
            field=models.DateField(null=True),
        ),
    ]
